### ISSUE TITLE
char on ARM

### ISSUE THREAD

**Issue by uncle-betty** [arminbiere/satch#9]
Just a quick heads-up: When compiling `satch` on 64-bit ARM Linux, some of the tests fail. The `satch` code assumes that `char` defaults to `signed`. On ARM, however, it defaults to `unsigned`.

Adding `-fsigned-char` to the compilation options fixes this.

(Well, strictly speaking, it's up to the compiler. But on ARM, compilers seem to chose `unsigned`.)

**Comment by arminbiere** [comment]
Thanks for reporting.  Usually I am careful about signedness of 'char' and 'int', but probably forgot here to be explicit.  I will try to reproduce it and fix it (worst was once 'struct s { int a : 30; int b : 2 };' is 'unsigned' on IBM mainframe compiler even though 'int' alone is of course signed - then 'struct s s; int a = -1; s.a = a; int sa = s.a; assert (sa == a);' failed).

**Comment by uncle-betty** [comment]
Thank you for your quick response. Oh, man, that bit field issue is pretty subtle!

I also try to be diligent when it comes to conversions, and I usually throw `-Wconversion` into the mix. I figured that I just need as much help as I can get from the compiler.

Something just occurred to me: If you don't have an ARM machine available to reproduce this, it's also possible to reproduce the issue on Intel by passing `-funsigned-char` to the compiler. I just double-checked.

**Comment by arminbiere** [comment]
Fixed in '0.5.6rc1' but only tested against '-funsigned-char' and not with an ARM compiler (nor cross-compiler).

**Comment by uncle-betty** [comment]
Great! Thank you for the fix. Works like a charm on my ARM machine. The tests pass with and without checks (`-c`).
